name: Build and Push Docker Image Image Java APP

on:
  push:
    tags:
      - 'v*'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Git tag as image tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -f Dockerfilejavapp -t marlonsevero/java-app:${{ steps.version.outputs.VERSION }} .

      - name: Push image to registry
        run: docker push marlonsevero/java-app:${{ steps.version.outputs.VERSION }}